ADSP: adsp::ApHp1 Class Reference
adsp::ApHp1 Class Reference
All-pass filter based on the RC high-pass, first-order.
#include "ApHp1.h"
Public Member Functions
void reset (double sampleRate)
Reset to default parameters, clear internal state and set sample rate.
double process (double x)
Proess a single sample.
void setSampleRate (double sampleRate)
Set sample rate, recalculate coefficients.
ApHp1Params getParameters ()
Get parameters.
void setParameters (const ApHp1Params &parameters)
Set parameters.
Protected Member Functions
void calculateFilterCoefficients ()
Recalculate coefficients, is called when filter parameters change.
Protected Attributes
double sampleRate {48000.0}
Sample rate.
Biquad biquad
Object implementing the difference equation.
double coefficientsArray [numCoefficients] = {0.0, 0.0, 0.0, 0.0, 0.0}
Filter coefficients.
ApHp1Params params
Filter parameters.
Detailed Description
All-pass filter based on the RC high-pass, first-order.
Analog modeled by means of a prewarped bilinear transformation.
Prewarping was chosen to match center frequencies.
This filter has not been decramped.
Definition at line 73 of file ApHp1.h.
Member Function Documentation
reset()
void adsp::ApHp1::reset (double sampleRate)
Reset to default parameters, clear internal state and set sample rate.
Parameters
sampleRate New sample rate
Definition at line 41 of file ApHp1.cpp.
{
     sampleRate = sampleRate;
     // Setup biquad object
     // Default implementation
     BiquadParams biquadParams = biquad.getParameters();
     biquadParams.calculationType = biquadAlgorithm::transposedCanonical;
     biquad.setParameters(biquadParams);
     // Clear biquad state array
     biquad.reset();
 }
References biquad, adsp::Biquad::getParameters(), and sampleRate.
process()
double adsp::ApHp1::process (double x)
Proess a single sample.
Parameters
x Input sample
Returns
Output sample
Definition at line 55 of file ApHp1.cpp.
 { return biquad.process(x); }
References biquad, and adsp::Biquad::process().
setSampleRate()
void adsp::ApHp1::setSampleRate (double sampleRate)
Set sample rate, recalculate coefficients.
Parameters
sampleRate
Definition at line 59 of file ApHp1.cpp.
{
     sampleRate = sampleRate;
     // Calculate new coefficients
     calculateFilterCoefficients();
 }
References calculateFilterCoefficients(), and sampleRate.
getParameters()
ApHp1Params adsp::ApHp1::getParameters ()
Get parameters.
Returns
Filter parameters
Definition at line 66 of file ApHp1.cpp.
 { return params; }
References params.
setParameters()
void adsp::ApHp1::setParameters (const ApHp1Params & parameters)
Set parameters.
Parameters
New filter parameters
Definition at line 68 of file ApHp1.cpp.
{
     // If new parameters differ..
     if (params.fc != parameters.fc) {
         // Update the parameters
         params = parameters;
         // Calculate coefficients with new parameters
         calculateFilterCoefficients();
     } else {
         // Otherwise do nothing
         return;
     }
 }
References calculateFilterCoefficients(), and params.
The documentation for this class was generated from the following files:
/home/butch/dev/plugin_dev/synx/ADSP/source/filter/ApHp1.h
/home/butch/dev/plugin_dev/synx/ADSP/source/filter/ApHp1.cpp