ADSP: adsp::OscTrivial Class Reference
adsp::OscTrivial Class Reference
Oscillator with trivially generated waveforms.
#include "OscTrivial.h"
Public Member Functions
void reset (double sampleRate)
Reinitialize oscillator with new sample rate.
OscTrivialParams getParams ()
Get oscillator parameters.
void setParams (const OscTrivialParams &_params)
Set parameters.
virtual OscTrivialOut renderOutputs ()
Render output (single sample per waveform)
void retrigger ()
Reset the internal phase accumulator (start waves from beginning)
Protected Member Functions
void wrap (double &counter)
Wrap counter if its value is larger than 1.0 (modulo)
Protected Attributes
OscTrivialParams params
Oscillator parameters.
double sampleRate {48000.0}
Internal sample rate.
double T = {1.0 / 48000.0}
Internal sampling interval.
double counter {0.0}
Modulo counter for the oscillator algorithms.
double counterTri {0.5}
Phase-aligned modulo counter for triangle wave.
double delta {0.0}
Counter step size (changes with oscillator freqeuncy)
Detailed Description
Oscillator with trivially generated waveforms.
Does not feature any form of aliasing prevention.
Outputs different waveforms simultaneously.
Can be retriggered and started at a given initial phase angle.
Works as an LFO.
Definition at line 100 of file OscTrivial.h.
Member Function Documentation
reset()
void adsp::OscTrivial::reset (double sampleRate)
Reinitialize oscillator with new sample rate.
Parameters
sampleRate New sample rate
Definition at line 41 of file OscTrivial.cpp.
{
     sampleRate = _sampleRate;
     T = 1.0 / _sampleRate;
     counter = 0.0;
     delta = 0.0;
     counterTri = 0.5;
 }
References counter, counterTri, delta, sampleRate, and T.
getParams()
OscTrivialParams adsp::OscTrivial::getParams ()
Get oscillator parameters.
Returns
Parameters
Definition at line 52 of file OscTrivial.cpp.
 { return params; }
References params.
setParams()
void adsp::OscTrivial::setParams (const OscTrivialParams & _params)
Set parameters.
Parameters
_params New parameters
Definition at line 54 of file OscTrivial.cpp.
{
     // Update params
     params = _params;
     // Calculate delta according to new frequency
     delta = _params.frequency * T;
 }
References delta, adsp::OscTrivialParams::frequency, params, and T.
renderOutputs()
OscTrivialOut adsp::OscTrivial::renderOutputs () virtual
Render output (single sample per waveform)
Returns
Next oscillator output
Definition at line 64 of file OscTrivial.cpp.
{
     //==============================================================================
     // SAW
     // Bipolar modulo counter
     counter += delta;
     wrap(counter);
     const double saw = unipolarToBipolar(counter);
     //==============================================================================
     // TRIANGLE
     // Rectify, scale and offset saw to create triangle
     // Offset counter to align phases between waveforms
     counterTri += delta;
     wrap(counterTri);
     const double sawTri = unipolarToBipolar(counterTri);
     const double tri = unipolarToBipolar(fabs(sawTri));
     //==============================================================================
     // PULSE
     const double pulse = (saw < 0.0) ? 1.0 : -1.0;
     //==============================================================================
     // Output
     OscTrivialOut output;
     output.saw = saw;
     output.tri = tri;
     output.pulse = pulse;
     return output;
 }
References counter, counterTri, delta, adsp::unipolarToBipolar(), and wrap().
wrap()
void adsp::OscTrivial::wrap (double & counter) protected
Wrap counter if its value is larger than 1.0 (modulo)
Parameters
counter Counter
Definition at line 109 of file OscTrivial.cpp.
{
     if (counter >= 1.0) {
         counter -= 1.0;
     }
 }
References counter.
Referenced by renderOutputs(), and retrigger().
The documentation for this class was generated from the following files:
/home/butch/dev/plugin_dev/synx/ADSP/source/oscillator/OscTrivial.h
/home/butch/dev/plugin_dev/synx/ADSP/source/oscillator/OscTrivial.cpp