ADSP: adsp::Biquad Class Reference
adsp::Biquad Class Reference
Biquadratic filter.
#include "Biquad.h"
Public Member Functions
void reset ()
Sets all state registers to zero
double process (double x)
Process a single sample
BiquadParams getParameters ()
Get the biquad parameters.
void setParameters (BiquadParams &_parameters)
Set new Parameters.
void setCoefficients (double *coefficients)
Set new coefficients.
double * getCoefficients ()
Get current coefficients.
double * getStateArray ()
Get current state array.
Protected Attributes
double coefficientsArray [numCoefficients] = {0.0, 0.0, 0.0, 0.0, 0.0}
Array of filter coefficients.
double stateArray [numRegisters] = {0.0, 0.0, 0.0, 0.0}
State array.
BiquadParams parameters
Biquad parameters.
Detailed Description
Biquadratic filter.
Second-order structure to filter input signals given a set of filter coefficients.
Different algorithms implementing the difference equation can be chosen.
Higher order filters are usually built up from multiple biquad stages.
Definition at line 108 of file Biquad.h.
Member Function Documentation
process()
double adsp::Biquad::process (double x)
Process a single sample
Uses difference equation implemented by the selected algorithm
Parameters
x Input sample
Returns
Output sample
Definition at line 47 of file Biquad.cpp.
{
     switch (parameters.calculationType) {
         // Direct form
         case biquadAlgorithm::direct: {
             // y[n] = a0*x[n] + a1*x[n-1] + a2*x[n-2] - b1*y[n-1] - b2*y[n-2]
             double y = coefficientsArray[a0] * x +
                        coefficientsArray[a1] * stateArray[x_z1] +
                        coefficientsArray[a2] * stateArray[x_z2] -
                        coefficientsArray[b1] * stateArray[y_z1] -
                        coefficientsArray[b2] * stateArray[y_z2];
             fixUnderflow(y);
             // Update state registers
             stateArray[x_z2] = stateArray[x_z1];
             stateArray[x_z1] = x;
             stateArray[y_z2] = stateArray[y_z1];
             stateArray[y_z1] = y;
             // Output
             return y;
         }
         // Canonical form, uses only two state registers
         case biquadAlgorithm::canonical: {
             // w[n] = x[n] - b1*w[n-1] - b2*w[n-2]
             double w = x - coefficientsArray[b1] * stateArray[x_z1] -
                        coefficientsArray[b2] * stateArray[x_z2];
             // y[n] = a0*w[n] + a1*w[n-1] + a2*w[n-2]
             double y = coefficientsArray[a0] * w +
                        coefficientsArray[a1] * stateArray[x_z1] +
                        coefficientsArray[a2] * stateArray[x_z2];
             fixUnderflow(y);
             // Update state registers
             stateArray[x_z2] = stateArray[x_z1];
             stateArray[x_z1] = w;
             // Output
             return y;
         }
         // Transposed direct form
         case biquadAlgorithm::transposedDirect: {
             // w[n] =  x[n] + stateArray[y_z1]
             double w = x + stateArray[y_z1];
             // y[n] = a0*w[n] + stateArray[x_z1]
             double y = coefficientsArray[a0] * w + stateArray[x_z1];
             fixUnderflow(y);
             // Update state registers
             stateArray[y_z1] = stateArray[y_z2] - coefficientsArray[b1] * w;
             stateArray[y_z2] = -coefficientsArray[b2] * w;
             stateArray[x_z1] = stateArray[x_z2] + coefficientsArray[a1] * w;
             stateArray[x_z2] = coefficientsArray[a2] * w;
             // Output
             return y;
         }
         // Transposed canonical form
         case biquadAlgorithm::transposedCanonical: {
             // y[n] = a0*x[n] + stateArray[x_z1]
             double y = coefficientsArray[a0] * x + stateArray[x_z1];
             fixUnderflow(y);
             // Update state registers
             stateArray[x_z1] = coefficientsArray[a1] * x -
                                coefficientsArray[b1] * y + stateArray[x_z2];
             stateArray[x_z2] =
                 coefficientsArray[a2] * x - coefficientsArray[b2] * y;
             // Output
             return y;
         }
         default: {
             return x;  // Did not process sample
         }
     }
 }
References parameters.
Referenced by adsp::ApHp1::process(), adsp::ApLp1::process(), adsp::RcHp1::process(), adsp::RcLp1::process(), adsp::SkHp2::process(), and adsp::SkLp2::process().
getParameters()
BiquadParams adsp::Biquad::getParameters ()
Get the biquad parameters.
Returns
Parameters
Definition at line 138 of file Biquad.cpp.
 { return parameters; }
References parameters.
Referenced by adsp::ApHp1::reset(), adsp::ApLp1::reset(), adsp::RcHp1::reset(), adsp::RcLp1::reset(), adsp::SkHp2::reset(), and adsp::SkLp2::reset().
setParameters()
void adsp::Biquad::setParameters (BiquadParams & _parameters)
Set new Parameters.
Parameters
_parameters New biquad parameters
Definition at line 140 of file Biquad.cpp.
{
     parameters = _parameters;
 }
References parameters.
setCoefficients()
void adsp::Biquad::setCoefficients (double * coefficients)
Set new coefficients.
Parameters
coefficients Array of filter coefficients
Definition at line 144 of file Biquad.cpp.
{
     memcpy(&coefficientsArray[0], &coefficients[0],
            sizeof(double) * numCoefficients);
 }
References coefficientsArray.
getCoefficients()
double * adsp::Biquad::getCoefficients ()
Get current coefficients.
Returns
Array of coefficients
Definition at line 149 of file Biquad.cpp.
 { return &coefficientsArray[0]; }
References coefficientsArray.
getStateArray()
double * adsp::Biquad::getStateArray ()
Get current state array.
Returns
State array
Definition at line 151 of file Biquad.cpp.
 { return &stateArray[0]; }
References stateArray.
The documentation for this class was generated from the following files:
/home/butch/dev/plugin_dev/synx/ADSP/source/filter/Biquad.h
/home/butch/dev/plugin_dev/synx/ADSP/source/filter/Biquad.cpp