ADSP: /home/butch/dev/plugin_dev/synx/ADSP/source/utility/utility.h File Reference
utility.h File Reference
Different dsp utility functions and useful constants.
#include <cmath>
Functions
template<typename T = double>
int adsp::sgn (T val)
sgn(x), the standard signum function.
bool adsp::fixUnderflow (double &d)
Fix possible float underflows before casting from double to avoid denormals.
double adsp::clip (double x, const double min=-1.0f, const double max=1.0f)
Clip value to given bounds.
float adsp::clip (float x, const float min=-1.0f, const float max=1.0f)
Clip value to given bounds.
void adsp::clipInPlace (double &x, const double min=-1.0, const double max=1.0)
Clip value in place to given bounds.
void adsp::clipInPlace (float &x, const float min=-1.0f, const float max=1.0f)
Clip value in place to given bounds.
double adsp::pitchToFreq (const double pitch)
Convert MIDI pitch (note number) to frequency.
float adsp::pitchToFreq (const float pitch)
Convert MIDI pitch (note number) to frequency.
double adsp::freqToPitch (const double freq)
Convert frequency to MIDI pitch (note number)
float adsp::freqToPitch (float freq)
Convert frequency to MIDI pitch (note number)
template<typename T = double>
T adsp::bipolarToUnipolar (T x)
Convert value from bipolar to unipolar range.
template<typename T = double>
T adsp::unipolarToBipolar (T x)
Convert value from unipolar to bipolar range.
double adsp::rawGainTodB (double gain)
Convert raw amplitude gain to decibels.
float adsp::rawGainTodB (float gain)
Convert raw amplitude gain to decibels.
double adsp::dbToRawGain (double dB)
Convert from decibels to raw amplitude gain.
float adsp::dbToRawGain (float dB)
Convert from decibels to raw amplitude gain.
double adsp::dbToRawGainOff (const double dB, const double offdB)
Convert from decibels to raw amplitude gain, clipping the signal when below a threshold.
float adsp::dbToRawGainOff (const float dB, const float offdB)
Convert from decibels to raw amplitude gain, clipping the signal when below a threshold.
template<typename T = double>
T adsp::linMap (const T val, const T inMin, const T inMax, const T outMin, const T outMax)
Linear mapping of one continuous range to another.
template<typename T = double>
T adsp::linMapNorm (const T val, const T outMin, const T outMax)
Linear mapping of value in [-1.0, 1.0] to another continuous range.
double adsp::skewNormalized (const double NormVal, const double skew)
Map a value in [0.0, 1.0] to the same interval with a skew factor.
float adsp::skewNormalized (const float NormVal, const float skew)
Map a value in [0.0, 1.0] to the same interval with a skew factor.
float adsp::fastLog2 (float val)
Faster (and less precise) log2 function.
Variables
constexpr double adsp::PI
constexpr double adsp::TWO_PI
constexpr double adsp::FRAC_ONE_PI = 1.0 / PI
const double adsp::SQRT_TWO = pow(2.0, 0.5)
const double adsp::FRAC_ONE_SQRT_TWO = pow(2.0, -0.5)
constexpr double adsp::MIN_FLOAT_VAL_POS = 1.175494351e-38
Smallest positive float value.
constexpr double adsp::MIN_FLOAT_VAL_NEG = -1.175494351e-38
Smallest negative float value.
constexpr double adsp::MIN_FILTER_FREQ = 20.0
Minimum filter cutoff frequency: 20 Hz (lower end of human hearing)
constexpr double adsp::MAX_FILTER_FREQ = 20480.0
Maximum filter cutoff frequency: 20480 Hz (10 octaves above 20 Hz)
Detailed Description
Different dsp utility functions and useful constants.
Definition in file utility.h.
Function Documentation
sgn()
template<typename T = double> int adsp::sgn (T val) inline
sgn(x), the standard signum function.
Template Parameters
T Integral or floating point type
Parameters
val Value to take the sign of
Returns
1 if val is positive, 0 if val is zero, -1 if val is negative
Definition at line 109 of file utility.h.
                       {
     return (static_cast<T>(0) < val) - (val < static_cast<T>(0));
 }
References adsp::sgn().
Referenced by adsp::sgn().
fixUnderflow()
bool adsp::fixUnderflow (double & d) inline
Fix possible float underflows before casting from double to avoid denormals.
Parameters
d double value to be checked for possible underflow
Returns
true if underflow was fixed
false if no underflow occured
Definition at line 122 of file utility.h.
{
     // Positive underflow
     if (d > 0.0 && d < MIN_FLOAT_VAL_POS) {
         // Fix to zero
         d = 0.0;
         return true;
     }
     // Negative underflow
     else if (d < 0.0 && d > MIN_FLOAT_VAL_NEG) {
         // Fix to zero
         d = 0.0;
         return true;
     }
     return false;
 }
References adsp::fixUnderflow(), adsp::MIN_FLOAT_VAL_NEG, and adsp::MIN_FLOAT_VAL_POS.
Referenced by adsp::fixUnderflow().
clip() [1/2]
double adsp::clip (double x, const double min = -1.0f, const double max = 1.0f) inline
Clip value to given bounds.
Parameters
x Value to be bounded
min Lower bound, defaults to -1.0
max Upper bound, defaults to 1.0
Returns
Clipped value
Definition at line 150 of file utility.h.
{
     // Clip upper bound
     x = fmin(max, x);
     // Clip lower bound
     x = fmax(min, x);
     return x;
 }
References adsp::clip().
Referenced by adsp::clip().
clip() [2/2]
float adsp::clip (float x, const float min = -1.0f, const float max = 1.0f) inline
Clip value to given bounds.
Parameters
x Value to be bounded
min Lower bound, defaults to -1.0
max Upper bound, defaults to 1.0
Returns
Clipped value
Definition at line 169 of file utility.h.
{
     // Clip upper bound
     x = fminf(max, x);
     // Clip lower bound
     x = fmaxf(min, x);
     return x;
 }
References adsp::clip().
clipInPlace() [1/2]
void adsp::clipInPlace (double & x, const double min = -1.0, const double max = 1.0) inline
Clip value in place to given bounds.
Parameters
x Value to be bounded
min Lower bound, defaults to -1.0
max Upper bound, defaults to 1.0
Definition at line 186 of file utility.h.
{
     // Clip upper bound
     x = fmin(max, x);
     // Clip lower bound
     x = fmax(min, x);
 }
References adsp::clipInPlace().
Referenced by adsp::clipInPlace().
clipInPlace() [2/2]
void adsp::clipInPlace (float & x, const float min = -1.0f, const float max = 1.0f) inline
Clip value in place to given bounds.
Parameters
x Value to be bounded
min Lower bound, defaults to -1.0
max Upper bound, defaults to 1.0
Definition at line 202 of file utility.h.
{
     // Clip upper bound
     x = fminf(max, x);
     // Clip lower bound
     x = fmaxf(min, x);
 }
References adsp::clipInPlace().
pitchToFreq() [1/2]
double adsp::pitchToFreq (const double pitch) inline
Convert MIDI pitch (note number) to frequency.
Parameters
pitch MIDI note number to convert (works for non-integer numbers!)
Returns
Corresponding frequency
Definition at line 220 of file utility.h.
{
     // Pitch 69 is A4:440.0 Hz
     return 440.0 * pow(2.0, (pitch - 69.0) / 12.0);
 }
References adsp::pitchToFreq().
Referenced by adsp::pitchToFreq().
pitchToFreq() [2/2]
float adsp::pitchToFreq (const float pitch) inline
Convert MIDI pitch (note number) to frequency.
Parameters
pitch MIDI note number to convert (works for non-integer numbers!)
Returns
Corresponding frequency
Definition at line 231 of file utility.h.
{
     // Pitch 69 is A4:440.0 Hz
     return 440.0f * powf(2.0f, (pitch - 69.0f) / 12.0f);
 }
References adsp::pitchToFreq().
freqToPitch() [1/2]
double adsp::freqToPitch (const double freq) inline
Convert frequency to MIDI pitch (note number)
Parameters
freq Frequency to convert
Returns
Corresponding MIDI pitch
Definition at line 242 of file utility.h.
{
     return 69.0 + 12.0 * log2(freq / 440.0);
 }
References adsp::freqToPitch().
Referenced by adsp::freqToPitch().
freqToPitch() [2/2]
float adsp::freqToPitch (float freq) inline
Convert frequency to MIDI pitch (note number)
Parameters
freq Frequency to convert
Returns
Corresponding MIDI pitch
Definition at line 252 of file utility.h.
{
     return 69.0f + 12.0f * log2f(freq / 440.0f);
 }
References adsp::freqToPitch().
bipolarToUnipolar()
template<typename T = double> T adsp::bipolarToUnipolar (T x) inline
Convert value from bipolar to unipolar range.
Template Parameters
T float or double
Parameters
x Bipolar value in range [-1.0, 1.0]
Returns
Corresponding unipolar value in range [0.0, 1.0]
Definition at line 267 of file utility.h.
{
     return static_cast<T>(0.5) * x + static_cast<T>(0.5);
 }
References adsp::bipolarToUnipolar().
Referenced by adsp::bipolarToUnipolar().
unipolarToBipolar()
template<typename T = double> T adsp::unipolarToBipolar (T x) inline
Convert value from unipolar to bipolar range.
Template Parameters
T float or double
Parameters
x Unipolar value in range [0.0, 1.0]
Returns
Corresponding bipolar value in range [-1.0, 1.0]
Definition at line 279 of file utility.h.
{
     return (x - static_cast<T>(0.5)) * static_cast<T>(2.0);
 }
References adsp::unipolarToBipolar().
Referenced by adsp::OscTrivial::renderOutputs(), and adsp::unipolarToBipolar().
rawGainTodB() [1/2]
double adsp::rawGainTodB (double gain) inline
Convert raw amplitude gain to decibels.
Parameters
gain Raw amplitude gain factor [1]
Returns
Corresponding decibel value [dB]
Definition at line 292 of file utility.h.
 { return 20.0 * log10(gain); }
References adsp::rawGainTodB().
Referenced by adsp::rawGainTodB().
rawGainTodB() [2/2]
float adsp::rawGainTodB (float gain) inline
Convert raw amplitude gain to decibels.
Parameters
gain Raw amplitude gain factor [1]
Returns
Corresponding decibel value [dB]
Definition at line 300 of file utility.h.
 { return 20.0f * log10f(gain); }
References adsp::rawGainTodB().
dbToRawGain() [1/2]
double adsp::dbToRawGain (double dB) inline
Convert from decibels to raw amplitude gain.
Parameters
dB Value to convert [dB]
Returns
Corresponding amplitude gain factor [1]
Definition at line 308 of file utility.h.
 { return pow(10.0, dB / 20.0); }
References adsp::dbToRawGain().
Referenced by adsp::dbToRawGain().
dbToRawGain() [2/2]
float adsp::dbToRawGain (float dB) inline
Convert from decibels to raw amplitude gain.
Parameters
dB Value to convert [dB]
Returns
Corresponding amplitude gain factor [1]
Definition at line 316 of file utility.h.
 { return powf(10.0f, dB / 20.0f); }
References adsp::dbToRawGain().
dbToRawGainOff() [1/2]
double adsp::dbToRawGainOff (const double dB, const double offdB) inline
Convert from decibels to raw amplitude gain, clipping the signal when below a threshold.
Parameters
dB Value to convert [dB]
offdB Off-threshold [dB]
Returns
Corresponding amplitude gain factor [1]
Definition at line 325 of file utility.h.
{
     return (dB >= offdB) * pow(10.0, dB / 20.0);
 }
References adsp::dbToRawGainOff().
Referenced by adsp::dbToRawGainOff().
dbToRawGainOff() [2/2]
float adsp::dbToRawGainOff (const float dB, const float offdB) inline
Convert from decibels to raw amplitude gain, clipping the signal when below a threshold.
Parameters
dB Value to convert [dB]
offdB Off-threshold [dB]
Returns
Corresponding amplitude gain factor [1]
Definition at line 336 of file utility.h.
{
     return (dB >= offdB) * powf(10.0f, dB / 20.0f);
 }
References adsp::dbToRawGainOff().
linMap()
template<typename T = double> T adsp::linMap (const T val, const T inMin, const T inMax, const T outMin, const T outMax) inline
Linear mapping of one continuous range to another.
(Linear interpolation)
Template Parameters
T float or double
Parameters
val Value to map
inMin Input lower bound
inMax Input upper bound
outMin Output lower bound
outMax Output range upper bound
Returns
Mapped value
Definition at line 357 of file utility.h.
{
     return (val - inMin) * (outMax - outMin) / (inMax - inMin) + outMin;
 }
References adsp::linMap().
Referenced by adsp::linMap().
linMapNorm()
template<typename T = double> T adsp::linMapNorm (const T val, const T outMin, const T outMax) inline
Linear mapping of value in [-1.0, 1.0] to another continuous range.
(Linear interpolation)
Template Parameters
T float or double
Parameters
val Normalised value to map
inMin Input lower bound
inMax Input upper bound
outMin Output lower bound
outMax Output upper bound
Returns
Mapped value
Definition at line 376 of file utility.h.
{
     return val * (outMax - outMin) + outMin;
 }
References adsp::linMapNorm().
Referenced by adsp::linMapNorm().
skewNormalized() [1/2]
double adsp::skewNormalized (const double NormVal, const double skew) inline
Map a value in [0.0, 1.0] to the same interval with a skew factor.
skew = 1 gives a linear map
skew in [0.0, 1.0[ gives more resolution in the lower range
skew in [1.0, INF[ gives more resolution in the upper range
Parameters
NormVal Normalised value to map
skew Skew factor
Returns
Mapped value
Definition at line 391 of file utility.h.
{
     return pow(NormVal, 1.0 / skew);
 }
References adsp::skewNormalized().
Referenced by adsp::skewNormalized().
skewNormalized() [2/2]
float adsp::skewNormalized (const float NormVal, const float skew) inline
Map a value in [0.0, 1.0] to the same interval with a skew factor.
skew = 1 gives a linear map
skew in [0.0, 1.0[ gives more resolution in the lower range
skew in [1.0, INF[ gives more resolution in the upper range
Parameters
NormVal Normalised value to map
skew Skew factor
Returns
Mapped value
Definition at line 406 of file utility.h.
{
     return powf(NormVal, 1.0f / skew);
 }
References adsp::skewNormalized().
fastLog2()
float adsp::fastLog2 (float val) inline
Faster (and less precise) log2 function.
Based on ideas on stack overflow by users Louis Geoffroy, CuriousGeorge and netvope
https://stackoverflow.com/questions/9411823/fast-log2float-x-implementation-c
Parameters
val Input value
Returns
log2(val)
Definition at line 422 of file utility.h.
{
     union {
         float val;
         int32_t x;
     } u = {val};
     float log_2 = (float)(((u.x >> 23) & 255) - 128);
     u.x &= ~(255 << 23);
     u.x += 127 << 23;
     log_2 += ((-0.34484843f) * u.val + 2.02466578f) * u.val - 0.67487759f;
     return (log_2);
 }
References adsp::fastLog2().
Referenced by adsp::fastLog2().
Variable Documentation
PI
constexpr double adsp::PI constexpr
Initial value:
=
    3.14159265358979323846264338327950288419716939937510582097494459230781640628620899
Definition at line 51 of file utility.h.
TWO_PI
constexpr double adsp::TWO_PI constexpr
Initial value:
=
    2.0 *
    3.14159265358979323846264338327950288419716939937510582097494459230781640628620899
Definition at line 57 of file utility.h.